### ISSUE TITLE
Does not print level as error

### ISSUE THREAD

**Issue by SalilLuley** [PayU/express-request-logger#42]
Hi. I see if error is thrown by an api/route (status code 500), the below code does not print level as error, it still prints it as info, I am using winston logger with the example code that is given in readme file.

Below is the code in index.ts
`const logger = createLogger({
  transports: [
    new transports.Console()
  ]
});

app.use(audit({
  logger: logger, // Existing bunyan logger
  excludeURLs: ["metrics", ], // Exclude paths which enclude 'health' & 'metrics'
  request: {
      maskBody: ["password"], // Mask 'password' field in incoming requests
      excludeHeaders: ["authorization"], // Exclude 'authorization' header from requests
      excludeBody: ["creditCard"], // Exclude 'creditCard' field from requests body
      maskHeaders: ["header1"], // Mask 'header1' header in incoming requests
      // maxBodyLength: 50 // limit length to 50 chars + '...'
  },
  response: {
      maskBody: ["session_token"], // Mask 'session_token' field in response body
      excludeHeaders: [""], // Exclude all headers from responses,
      excludeBody: [""], // Exclude all body from responses
      maskHeaders: ["header1"], // Mask 'header1' header in incoming requests
      // maxBodyLength: 50 // limit length to 50 chars + '...'
  }
}));`

Below is the log printed.
`level info
message {
  response: {
    status_code: 500,
    timestamp: '2021-03-30T20:17:05.308Z',
    timestamp_ms: 1617135425308,
    elapsed: 2,
    headers: {
      'content-security-policy': "default-src 'none'",
      'x-dns-prefetch-control': 'off',
      'expect-ct': 'max-age=0',
      'x-frame-options': 'SAMEORIGIN',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'x-permitted-cross-domain-policies': 'none',
      'referrer-policy': 'no-referrer',
      'x-xss-protection': '0',
      'access-control-allow-origin': '*',
      'content-type': 'text/html; charset=utf-8',
      'content-length': 1241
    },
    body: '<!DOCTYPE html>\n' +
      '<html lang="en">\n' +
      '<head>\n' +
      '<meta charset="utf-8">\n' +
      '<title>Error</title>\n' +
      '</head>\n' +
      '<body>\n' +
      '<pre>Error: This is an error<br> &nbsp; &nbsp;at D:\\Workspace\\Node\\Currency\\src\\routers\\CurrencryRates.routes.ts:10:9<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at next (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\layer.js:95:5)<br> &nbsp; &nbsp;at D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\index.js:335:12)<br> &nbsp; &nbsp;at next (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\index.js:275:10)<br> &nbsp; &nbsp;at Function.handle (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\index.js:174:3)<br> &nbsp; &nbsp;at router (D:\\Workspace\\Node\\Currency\\node_modules\\express\\lib\\router\\index.js:47:12)</pre>\n' +
      '</body>\n' +
      '</html>\n'
  },
  request: {
    method: 'GET',
    url_params: 'N/A',
    url: '/currencyRates?from=EUR&to=INR',
    url_route: 'N/A',
    query: { from: 'EUR', to: 'INR' },
    headers: {
      'content-type': 'application/json',
      'user-agent': 'PostmanRuntime/7.26.10',
      accept: '*/*',
      'postman-token': '2b578982-4d37-417c-9206-5984df1e4ee7',
      host: 'localhost:3000',
      'accept-encoding': 'gzip, deflate, br',
      connection: 'keep-alive',
      'content-length': '41'
    },
    timestamp: '2021-03-30T20:17:05.306Z',
    timestamp_ms: 1617135425306,
    body: '{"dummy":"This is loreum ispum"}'
  },
  'millis-timestamp': 1617135425312,
  'utc-timestamp': '2021-03-30T20:17:05.312Z',
  stage: 'end'
}
Error: This is an error
    at D:\Workspace\Node\Currency\src\routers\CurrencryRates.routes.ts:10:9
    at Layer.handle [as handle_request] (D:\Workspace\Node\Currency\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Workspace\Node\Currency\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Workspace\Node\Currency\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Workspace\Node\Currency\node_modules\express\lib\router\layer.js:95:5)
    at D:\Workspace\Node\Currency\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Workspace\Node\Currency\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Workspace\Node\Currency\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Workspace\Node\Currency\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Workspace\Node\Currency\node_modules\express\lib\router\index.js:47:12)`

**Comment by omer182** [comment]
Hey there @SalilLuley how are you?
This package runs and tested on [Bunyan](https://www.npmjs.com/package/bunyan) logger only.  
You can give it a try :)
